### ISSUE TITLE
Dynamically set Test Variables not found

### ISSUE THREAD

**Issue by myjniak** [jnhyperion/HyperRobotFrameworkPlugin#65]
I am aware this might be a little bit controversial, but... it works in another Robot plugin, so I'll give it a shot :D

```robot
*** Test Cases ***
Test1
    Test1 Setup
    Log To Console    ${NICE}
    
*** Keywords ***
Test1 Setup
    Set Test Variable    ${NICE}  very nice
```
![image](https://github.com/jnhyperion/HyperRobotFrameworkPlugin/assets/39498464/20515999-80ad-48bb-84f4-285614d3d718)

Is this expected?
Suite and Global variables behave the same way.

**Comment by jnhyperion** [comment]
I think plugin will never know the dynamically created variables, because this requires the kw runtime execution, while the plugin only does the code static analysis.

If the dynamically created variables can be resolved somehow, I can say it's only some kind of prediction, and I don't like it, because it could mislead you sometimes.

**Comment by jnhyperion** [comment]
For now, the plugin supports the global variable parsing in `__init__.robot`
example:
`__init__.robot`
``` robot
*** Settings ***
Suite Setup    Set Global Variable    ${global}    foo
```
then any robot file in the sub folder under the `__init__.robot` location can parse `${global}`

**Comment by myjniak** [comment]
I understand, I think this issue can be closed then :)
