### ISSUE TITLE
Support for extensions that rely on robotframework-pythoncore

### ISSUE THREAD

**Issue by takeda** [jnhyperion/HyperRobotFrameworkPlugin#67]
There is a library that allows to bigger extension to be split into smaller pieces:
https://github.com/robotframework/PythonLibCore

It looks like this plugin doesn't understand sub-libraries, so it shows keywords from them as errors.

**Comment by jnhyperion** [comment]
It's because the sub libraries are loaded dynamically in robot runtime. In this case, the library should provide a `pyi` file to enable IDE to parse the method signatures.

For example: 
[SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L57)

and it's pyi file:
[`__init__.pyi`](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.pyi#L8)
